import turtle
import math
def RainbowHouse () :
  wn=turtle.Screen()
  turtle.title("Yellow House")
  wn.bgcolor("White")
  #sideLength = 200
  house=turtle.Turtle()
  Diagonal_length= 0.5*math.sqrt(2 *(200 ** 2 ))
  turtle.pensize(5)
  turtle.speed(4.6)
  turtle.color("Orange")
  turtle.left(90)
  turtle.forward(200)
  turtle.right (135)
  turtle.color("Blue")
  turtle.forward(Diagonal_length)
  turtle.right(90)
  turtle.color("Red")
  turtle.forward(Diagonal_length)
  turtle.left(135)
  turtle.color("Cyan")
  turtle.forward(200)
  turtle.left(135)
  turtle.color("Green")
  turtle.forward(Diagonal_length)
  turtle.right(90)
  turtle.color("Grey")
  turtle.forward(Diagonal_length)
  turtle.left(135)
  turtle.color("Yellow")
  turtle.forward(200)
  turtle.right(135)
  turtle.color("Purple")
  turtle.forward(Diagonal_length)
  turtle.right(90)
  turtle.color("Black")
  turtle.forward(Diagonal_length)
  turtle.right(45)
  turtle.color("Magenta")
  turtle.forward(200)
  turtle.left(90)
  wn.mainloop()
RainbowHouse ()
